### ISSUE TITLE
Suggestion on Plugin Deployer by using RegisterFile.crmregister file

### ISSUE THREAD

**Issue by timewizard88** [jlattimer/D365DeveloperExtensions#26]
Hello Jlattimer,

First, I really appreciate your D365 Developer Extension. It's really good for Front End development with Web Resource Deployer.

For Plugin Deployer can you make some improvements: Use the configuration file with the similar data in RegisterFile.crmregister file (from MS Dynamic 365 Developer Toolkit).
1. Personally, I think that file is very clear and explicit configure all the plugins, steps and images information.
2. Using Regex to classify the plugin is hard and tedious... Not every programmer can read regex. List all the elements explicit is easier, do you agree?
3. My co-worker had some serious issue when deploy a plugin step with image, and it's crash all the time so we need to Plugin Registration tool manually.

BTW, do we have schema for spkl json file? 

Regards,
Giang

**Comment by jlattimer** [comment]
Thanks for the feedback.

You should realize I've adopted the spkl.json mapping file as Scott is using in his [SPKL ](https://github.com/scottdurow/SparkleXrm)deployment framework just so the it can be re-used between command line and this extension. So really, additional information or any comments specific to that should be directed there. 

With that said, I'm not going to change the format to what the MS Developer Toolkit uses since they basically don't support it and since the beginning I never thought it really worked all that great or at least the tooling around it was awful. 

Regex isn't ideal, but most people don't use more than 2 base classes (1 plug-in & 1 WF) so once it's figured out it really shouldn't be an issue in the long term. If you've got a better solution, I suggest you code it up and submit a PR on the SPKL project. 

Is you co-worker using the latest version of the extension? If not have them do so as it fixed some plug-in deployment issues. If using latest and still having issues, have them open a new issue and give me something so I can repro the issue.

**Comment by timewizard88** [comment]
Thanks for your reply,

Yes, I know that if you do the improvement, it will break the spkl
compatible. I'll make the suggest with Scott in his github for alternative
configuration.

The reason I ask for spkl schema is actually I don't know how to configure
plugin image and its attributes. We can't rely on tutorial so a schema with
self-explanatory would help developer to know all spkl tool's useful
functions. Think about this suggestion again, it should be in Scott's
github too.

Thanks,
Giang
