### ISSUE TITLE
Does not recognize JS files which are not in the solution (ie- files generated from TS)

### ISSUE THREAD

**Issue by jdimarzio** [jlattimer/D365DeveloperExtensions#6]
When generating JS web resources from TypeScript, I don't include my JS files in my solution that gets checked into source control.  This results in them not being able to be mapped.  If I include the file in my solution, i can map it... but removing the item from the solution unmaps my files.

I'd like for the extension to essentially recognize TS files as JS.

**Comment by jlattimer** [comment]
What if maybe we looked at the .tsconfig's "outFile" and included the JS files in that folder in the list of files to map? The one drawback would be that if you edit the .tsconfig and change the path, you'd probably have to reconnect or reload in order to trigger the file list to be regenerated. Project files are added/updated/deleted as a result of events firing on the project. I'm not sure I'd want to put a listener on the file looking for changes so the file list could be created correctly each time you open the file list. 

The other option is showing the TS files in the file list and building in logic to look for a corresponding JS in the project directory (but not necessarily in the actual project) and just pull those content when needed.

**Comment by jdimarzio** [comment]
@jlattimer  i think the second option would be perfect!  I believe the last iteration of the tool actually did that.

**Comment by jlattimer** [comment]
Yeah - I think I missed bringing that over. I'll do that then

**Comment by jlattimer** [comment]
Ended up adding a "ts" attribute to the spkl.config file to keep track with which TypeScript and JavaScript files go together. Also removed the functionality the previously would remove mappings if the local or CRM file was missing. Instead if sets a new "Lock" attribute on the web resource in the grid to ensure it keeps reading from the config file. This also lets you edit the config file manually and not have to worry about the mapping being wiped out because the file was not actually part of the project.
